### PR TITLE
added javascript shims for bootstrap to work with jQuery 1.7

### PR DESCRIPTION
**Pull request by thiagodemellobueno**
Explanations in the README.md
I havent added the JS to the info file, as I imagine we should compile these down first (maybe along with the ctools modal override into a general compatability layer).

I'm happy to workshop this for eventual inclusion.

### CODE REVIEW

**Comment by pirog** [comment]
@labboy0276 since both you and @madeofpeople have worked on this problem could you do some QA here and let me know if this works.

@madeofpeople i think including the JS directly to the info file in 3.x is fine since there is no compilation happening in this version. In the master branch (which is the branch that generates 4.x) there may be more logical places to put these things pre-compile.

**Comment by thiagodemellobueno** [comment]
@pirog, sure let's talk about it.

@labboy0276, our solutions for the collapse issue are much the same, i'm jsut overriding the prototype constructor (so its less a case-by-case fix) and more 'anywhere collapse appears' which also covers accordions etc.

**Comment by pirog** [comment]
@madeofpeople i'll be traveling today but back in action tomorrow. ping me when you have time and we can figure out the best place to put this.... would like to focus on master/4.x as 3.x is end of life.

**Comment by labboy0276** [comment]
@madeofpeople OK?

**Comment by thiagodemellobueno** [comment]
@pirog will do, lets schedule a time for the morrow.

**Comment by pirog** [comment]
im not sure if i can do today. ping me on the slacks sometime so we can
discuss a good time.

On Mon, Oct 6, 2014 at 12:17 PM, Thiago de Mello Bueno <
notifications@github.com> wrote:

> @pirog https://github.com/pirog will do, lets schedule a time for the
> morrow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/pull/150#issuecomment-58076979
> .

## 

Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Pull request closed without merging**
