### PR TITLE
THROBBER!

### PR DESCRIPTION
**Pull request by soniktrooth**
Bringing back the throbbing functionality on autocomplete text fields.

### CODE REVIEW

**Comment by soniktrooth** [comment]
To test this you can just add an entity reference field to a content type.

**Comment by pirog** [comment]
@soniktrooth 
The only thing that i can see here is we might just want to set it up so people can't toggle off fontawesome anymore. If they did that presumably this would break?

**Comment by soniktrooth** [comment]
It wouldn't so much break as just not have a throbber–as is the case ATM. I'm happy to run with FA requirement as we discussed the other day though.

**Comment by pirog** [comment]
right. 

so either we 
1. use the default drupal throbber when FA is not on
2. just always make sure FA is on

the choice is yours. we can do it in this PR or merge this in and you can open a new issue for this thing.

**Comment by soniktrooth** [comment]
I like the idea of getting the Drupal one if there's no FA. Ideas for passing this knowledge through the css? Maybe add a body class when FA is added?

**Comment by pirog** [comment]
despite my loathing of the normal throbber i agree that this is probably the best thing to do. 

could preprocess the field(s) that have the throbber and add the FA or drupal class based on the theme setting? Not sure if that would work in this case but it would be pretty easy.

**Comment by soniktrooth** [comment]
Ah, it's a theme setting that is taking care of adding FA. That's good—sounds like the best approach. I share your disdain for normal throbber but something is better than nothing when it comes to UX.

I will add some code to this so don't merge yet.

**Comment by pirog** [comment]
i await all the code

**Comment by soniktrooth** [comment]
I've said the word 'throbber' far too many times this week. @pirog wanna check this out now?

**Comment by pirog** [comment]
haha seriously right? yeah this looks good to me!

**Pull request merged**
