### PR TITLE
Fix bootswatch scheme issue

### PR DESCRIPTION
**Pull request by soniktrooth**
Addresses #176

### CODE REVIEW

**Comment by pirog** [comment]
looks good but getting sloppy on those drupal indent space standards?

**Comment by soniktrooth** [comment]
My editor was having a brain fart—it didn't look like that on screen.

**Comment by pirog** [comment]
and it looks the same even after your change now so maybe something strange is happening in translation? maybe github is rendering your stuff as tabs instead of spaces?

**Comment by soniktrooth** [comment]
Super weird. I think that's good now though.

**Comment by pirog** [comment]
oh yeah! there it is.
no words. so beautiful. https://www.youtube.com/watch?v=ACKWK55Ic9M

**Comment by soniktrooth** [comment]
I'm tha code poet, bee-atch.

**Pull request merged**
