### PR TITLE
Drupal Coding Standards Refactor

### PR DESCRIPTION
**Pull request by bassettsj**
- [x] refactor our code to fit [Drupal Coding Standards](https://www.drupal.org/coding-standards)
- [x] add task to Travis CI for Q/A on pull requests
- [x] add to [CONTRIBUTE.md](https://github.com/drupalprojects/kalatheme/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by bassettsj** [comment]
@pirog & @labboy0276 maybe we can help go through the coding standards refactor to be able to require any new code changes to fit the the Drupal coding standards and make it more consistent. You can pull my branch down and start working on it. I think you can pull request my branch even.

**Comment by pirog** [comment]
@bassettsj i'm probably going to be somewhat MIA on KT going forward. Just wanted to plow through those last 3.x issues. Going forward @labboy0276 and possibly @reynoldsalec should be your men!

**Comment by bassettsj** [comment]
Well dang, I did it all, one by one. If the travis CI passes, I will merge the changes into master.

**Comment by pirog** [comment]
@bassettsj wow! is this something we can/should do in 3.x as well?

**Pull request merged**
