### PR TITLE
#155 fix page.tpl for new radix layout based panopoly

### PR DESCRIPTION
**Pull request by labboy0276**

### CODE REVIEW

**Comment by reynoldsalec** [comment]
I think I misled you here @labboy0276; could you apply this to the https://github.com/kalamuna/kalatheme-source project when you get a chance? Thanks!

**Comment by pirog** [comment]
@reynoldsalec @labboy0276 what is the status of this? 

its up to @soniktrooth but i think we plan to deprecate https://github.com/kalamuna/kalatheme-source ? in which case we probably want to merge this here?

**Comment by labboy0276** [comment]
@pirog It was never merged, I would just merge this and all will be well.  Can do the same for kalatheme-source as well if need be.

**Comment by pirog** [comment]
i will leave this up to @soniktrooth for merging but thanks for the update.

**Pull request merged**
