### PR TITLE
Links to new wiki

### PR DESCRIPTION
**Pull request by katypool-zz**
This is just replacing to d.o. links with the links to the wiki, and changing some of the outdated info in the Readme. Not sure if we wanted to have more info in the readme itself, but i feel like linking to the extensive wiki might be enough (& that way it stays centralized).

### CODE REVIEW

**Comment by pirog** [comment]
@katypool this works for me but i'll let @bassettsj be the ultimate arbiter of wisdom here. whatever we do lets make sure this gets backported to 3.x. 

@katypool should i close https://github.com/drupalprojects/kalatheme/pull/117 in favor of this and a subsequent backport or does #117 contain something that is not in here?

**Comment by katypool-zz** [comment]
Yeah, go ahead and close it.

**Comment by reynoldsalec** [comment]
This looks good @katypool , FYI @bassettsj, Katy got rid of a couple annoying notices on the newer commit in this Pull Request.

**Comment by pirog** [comment]
This all looks solid to me. Going to merge but let's make sure we backport to 3.x as well!

**Pull request merged**
