### PR TITLE
GBZ3-237 Fix array checking _kalatheme_get_styles

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by soniktrooth** [comment]
@RobLoach  do you know under what circumstances that `$styles` wasn't an array?

**Comment by RobLoach** [comment]
I believe it was coming from a .info file or somewhere. Faulty API use, but you should never assume inputs are kosher.

**Comment by soniktrooth** [comment]
I'm unfamiliar with the Faulty API—are there docs?

**Comment by RobLoach** [comment]
http://drupal.org/project/faulty ... Seems they unpublished it.

**Comment by soniktrooth** [comment]
Either that or the page is...wait for it...faulty!

**Pull request merged**
