### PR TITLE
7.x 3.x README changes 

### PR DESCRIPTION
**Pull request by katypool-zz**
Updating the README to include links to the wiki instead of outdated d.o. documentation

### CODE REVIEW

**Comment by andrewmallis** [comment]
We are advising jquery update 1.7+ here. Although Boostrap requires 1.9+
https://github.com/twbs/bootstrap/blob/v3.2.0/bower.json
That version actually breaks IPE components, so we should instead be explicit about that requirement here.

ping @bassettsj on this

**Comment by pirog** [comment]
good catch @andrewmallis we should def provide some sort of language about this mismatch and what people can do about it. Let's try to get something like that in there and then we can merge all the new docs in!

**Comment by pirog** [comment]
@katypool how does #116 differ from #117 here? Which one should we be looking at?

**Comment by katypool-zz** [comment]
should be looking at #117 . I'll close this one to avoid confusion

**Pull request closed without merging**
