### PR TITLE
Missing comma breaks menu_local_task markup

### PR DESCRIPTION
**Pull request by soniktrooth**
This didn't seem to be disastrous when I was looking at it in Chrome but I imagine it could kill and older browser.

### CODE REVIEW

**Comment by pirog** [comment]
im a little out of the loop on this so it would be great to get the thumbs up from either @madeofpeople @robloach or @andrewmallis

**Comment by andrewmallis** [comment]
inspecting the code, it does look like this is a legit typo.
Have not QA'd it though, so no explicit thumbs up. Rather a one-handed clap :hand:

**Comment by soniktrooth** [comment]
If I do one too then it can be a high five and that's better than thumbs up :hand:

**Comment by thiagodemellobueno** [comment]
::hand:: ::hand::

**Comment by soniktrooth** [comment]
This is tested and working over on CITC—can someone merge it? I don't have write access yet.

**Comment by pirog** [comment]
done

also @soniktrooth i gave you write acess

**Pull request merged**
