### PR TITLE
Applying patch from kalamuna playbox issue #68

### PR DESCRIPTION
**Pull request by danlinn**
This applies the same patch (different line numbers) that was merged in playbox #68 https://github.com/kalamuna/playbox/commit/25658472bb6bf86a91883141fa9dce253eb9e7bf

### CODE REVIEW

**Comment by pirog** [comment]
seems reasonable and LGTM! let @andrewmallis or @soniktrooth do the PR.

@danlinn OMSI being the Oregon Museum of Science and Industry?

**Comment by danlinn** [comment]
Yes, that's us!

**Comment by pirog** [comment]
Awesome! I love OMSI :) been there a few times. 

Def hit up Kalamuna if you guys need any help with Drupal or Wordpress things. We'd love to help!

**Comment by RobLoach** [comment]
The scope for `$responsive_toggle` is incorrect. It's defined in the loop, but then used at a diffferent scope. If there are no elements in the loop to process, $responsive_toggle will not be defined.

**Comment by soniktrooth** [comment]
@RobLoach can you see a way to fix the scoping or is this just incorrect logic?

**Comment by soniktrooth** [comment]
LMAO I just realised the original PR was by me. Maybe I shouldn't have got the job after all :smile:

**Comment by soniktrooth** [comment]
I really don't remember what this was all about but I wonder if it's just a matter of defining `$responsive_toggle_off` outside of the foreach?

**Comment by pirog** [comment]
@soniktrooth i could be completely off here but why do we even have "responsive toggle" still? Why not just purge it completely? 

FIRE FIRE FIRE FIRE!
https://www.youtube.com/watch?v=XchwE9zVdnw

**Comment by soniktrooth** [comment]
This PR is against 4.x branch which is no longer supported. Closing in favour of #246

**Pull request closed without merging**
