### PR TITLE
Better handling of menu list item attributes.

### PR DESCRIPTION
**Pull request by soniktrooth**
Also enables support for menu_attributes module.

### CODE REVIEW

**Comment by pirog** [comment]
@soniktrooth is this good to go? what do we need to proceed with merging?

**Comment by soniktrooth** [comment]
@pirog Some testing wouldn't go astray I guess

**Comment by pirog** [comment]
maybe @labboy0276 would be down to do that and give a +1?

**Comment by labboy0276** [comment]
ok maybe tomm, but not today, you will have to remind me fo sho

On Tue, Jul 21, 2015 at 2:16 PM, Mike Pirog notifications@github.com
wrote:

> maybe @labboy0276 https://github.com/labboy0276 would be down to do
> that and give a +1?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupalprojects/kalatheme/pull/184#issuecomment-123422212
> .

## 

_John Ouellet_
_Sr Developer & Support Manager_
415-470-3076
www.kalamuna.com

Stay connected with Kalamuna on: Twitter
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
, Linkedin
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9,
and Facebook
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9

**Comment by soniktrooth** [comment]
ping @labboy0276

**Pull request merged**
